name: deploy-container

on:
  push:
    branches:
      - main
    paths:
      - "container/**"
defaults:
  run:
    working-directory: ./container
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls -la
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
      - run: pnpm install
      - run: pnpm run build
      - uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: sync
          source: dist
          destination: s3:${{secrets.AWS_S3_BUCKET_NAME}}/container/latest
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
